---
title: "Case II"
author: "Lina Simonian & Elena Pshenichnikova"
output: html_document
date: "2025-03-27"
---

```{r, include=FALSE}

# clear the database
rm(list=ls()) 
graphics.off()

```

```{r setup, include=FALSE, results = "hide"}

#Readability in HTML report
#install.packages("DT")
library(DT)

# Clear the database
rm(list=ls()) 

#Install necessary packages. Delete # sign in order to download all of them. 
#install.packages('rcompanion', repos = "https://cloud.r-project.org")
#install.packages('nortest', repos = "https://cloud.r-project.org")
#install.packages('corrplot', repos = "https://cloud.r-project.org")
#install.packages('olsrr', repos = "https://cloud.r-project.org")
#install.packages('dplyr', repos = "https://cloud.r-project.org")
#install.packages('pastecs', repos = "https://cloud.r-project.org")
#install.packages('REdaS', repos = "https://cloud.r-project.org")
#install.packages('psych', repos = "https://cloud.r-project.org")
#install.packages('lm.beta', repos = "https://cloud.r-project.org")


# Load required libraries
library(ggplot2)
library(dplyr)
library(readr)
library(broom)
library(lm.beta)
library(pastecs)
library(tidyr)
library(corrplot)     # Correlation matrix plot
library(olsrr)        # VIF and Tolerance Values
library(REdaS)        # Bartelett's Test
library(psych)

```

```{r, include=FALSE, results = "hide"}
# Reading the data
url <- "https://raw.githubusercontent.com/silinette/Case-Study-II/refs/heads/main/Data%20File_Case_Study_Factor%20Analysis_MD.csv"
Data <- read.csv(url, header = TRUE)
Data
```

```{r}
dim(Data) # Check the number of rows and columns in the dataset
head(Data) # Display the first few rows of the dataset
str(Data) # Display the structure of the dataset (types, sample values)
names(Data) # Show all variable names in the dataset
```

```{r}
list_na <- colnames(Data)[apply(Data, 2, anyNA)] # Identify columns with missing values
list_na 
sum(is.na(Data)) # Count total number of missing values
```
# Как убрать NA variables
```{r}
round(stat.desc(Data), digits=3) # Compute descriptive statistics (without normality test)
#Убрала NORM
```
```{r}
# Reshape the data into long format for visualization
data_long <- Data %>%
  pivot_longer(everything(), names_to = "Item", values_to = "Response")
# Preview reshaped data
head(data_long)

# Convert responses to ordered factor
data_long$Response <- factor(data_long$Response, levels = sort(unique(unlist(Data))))

# Plot response distributions for all items
ggplot(data_long, aes(x = Response)) +
  geom_bar(fill = "steelblue") +
  facet_wrap(~ Item, scales = "free_y") +
  labs(title = "Distributions", x = "Response", y = "Count") +
  theme_minimal()

```


```{r, echo=FALSE, message = FALSE}
#Residuals
par(mfrow = c(2, 2))
plot(Data)
#should be removed
```

```{r, echo=FALSE, message = FALSE}

raqMatrix <- cor(Data)
corrplot(as.matrix(raqMatrix))

```
```{r, echo=FALSE, message = FALSE}

# Bartlett's Test, KMO, Anti-image Correlation 

#Bartlett-Test
#bart_spher(Data[2:31])

```

```{r, echo=FALSE, message = FALSE}

kmo_test = KMOS(Data[2:31])
kmo_test


#KMO Criterion
kmo_test$KMO

#Anti-Image Correlations
kmo_test$MSA
sort(kmo_test$MSA) #sorted

```

```{r, echo=FALSE, message = FALSE}

PC0 <- principal(Data[, 2:31], 
                 rotate="varimax", 
                 scores=TRUE)

PC0$values #eigenvalues

plot(PC0$values, xlab="Factor Number", ylab="Eigenvalue",
     main="Scree plot",
     cex.lab=1.2, cex.axis=1.2, cex.main=1.8)+
  abline(h=1)

PC0_communalities <- data.frame(sort(PC0$communality))
PC0_communalities


```

```{r, echo=FALSE, message = FALSE}

# Principal components analysis with varimax rotation

PC1 <- principal(Data[, 2:31], 
                        rotate="varimax",
                        nfactors=9, 
                        scores=TRUE)

EigenValue_pc1 <- PC1$values
EigenValue_pc1 

PC1_communalities=data.frame(sort(PC1$communality))
PC1_communalities

```

```{r, echo=FALSE, message = FALSE}

EigenValue <- PC1$values

Variance <- EigenValue/ncol(subset(Data, select = c(x1:x30)))*100

SumVariance <- cumsum(EigenValue/ncol(subset(Data, select = c(x1:x30))))


Total_Variance_Explained <- cbind(EigenValue=EigenValue[EigenValue>0],
                                  Variance=Variance[Variance>0],
                                  Total_Variance=SumVariance[Variance>0])
Total_Variance_Explained

```

```{r, echo=FALSE, message = FALSE}

print(PC1$loadings, cutoff=0.3, sort=TRUE)

```